### ISSUE TITLE
`GetCoverage` on ODC with `subset` parameters fails with 502 Bad Gateway Error

### ISSUE THREAD

**Issue by erwagasore** [WFP-VAM/prism-frontend#216] opened 2021-06-21 18:07 UTC
`GetCoverage` request on ODC with subset `latitude`, `longitude`, and `time` results in 502 Bad Gateway.

Details:
- Those subsets are defined in `DescribeCoverage` as `AxisLabels` you can find them [here](https://odc.ovio.org/?service=WCS&request=DescribeCoverage&version=2.0.0&coverageId=hfs1_sfw_mask)

- e.g. [`GetCoverage` request on `hfs1_sfw_mask` CoverageID](https://odc.ovio.org/?service=WCS&request=GetCoverage&version=2.0.1&coverageId=hfs1_sfw_mask&subset=longitude(92.17274709800029,101.17001505562291)&subset=latitude(9.67125210200021,28.545538862)&subset=time(%222021-05-03T10:00:00.000Z%22))

<img width="1282" alt="Screen Shot 2021-06-21 at 7 46 08 PM" src="https://user-images.githubusercontent.com/1290048/122805946-00962a00-d2ca-11eb-9af5-7d032c776ea3.png">

**Comment by erwagasore** [comment] 2021-06-21 18:14
I suspect that the issue is related to `request limit` described [here](https://docs.geoserver.org/stable/en/user/services/wcs/configuration.html#request-limits)

**Comment by erwagasore** [comment] 2021-06-21 18:24
On one occasion I didn't get a `502 Bad Gateway` error I got the exception below from the server which confirms the point in above comment.

<img width="1192" alt="Screen Shot 2021-06-21 at 7 19 22 PM" src="https://user-images.githubusercontent.com/1290048/122809342-48b74b80-d2ce-11eb-8f24-170b4da80e56.png">

**Comment by wadhwamatic** [comment] 2021-06-21 20:15
@valpesendorfer - can you have a look at this issue?

**Comment by valpesendorfer** [comment] 2021-06-21 22:19
There's no limit set - in fact that is what the issue might be. The array resulting for your request is over the limits what the server can handle, essentially killing the worker and resulting in a re-boot of the service. Ideally, this should be handled gracefully by imposing some limits.

The question for me is, why your array has the `float64` datatype, which is the reason for the total size. The native datatype is `uint8` - I don't know if this get's overridden somewhere, or if the requests defaults in it or if there's added configuration on the server side needed.

Need to have a closer look into the configuration - but I'm not surprised this request fails with a 5xx response

**Comment by wadhwamatic** [comment] 2021-06-22 16:47
Thanks for looking into this @valpesendorfer. Clearly problematic that we are trying to allocate 17.4 GB for an array. To my knowledge, we are not specifying datatype in the request. @erwagasore and @JorgeMartinezG - can you please confirm?

If this is on the PRISM side, I'd like to get this resolved this week please. 

cc: @ericboucher

**Comment by JorgeMartinezG** [comment] 2021-06-22 17:00
For wcs 2.0 on PRISM we only include **extent** and **time** as subsets according to spec. The idea is to remove width and height parameters within the request

**Comment by wadhwamatic** [comment] 2021-06-22 17:10
Thanks Jorge. Given that we're only specifying extent and time, this might be an issue on ODC side with the datatype. @valpesendorfer - perhaps this is indeed a configuration server side to specify the datatype for the response?

**Comment by valpesendorfer** [comment] 2021-06-22 18:36
@JorgeMartinezG @erwagasore Can anyone provide a request that was working with the `width` and `height` parameters and the corresponding one using `extent` which reproduces the error?

**Comment by JorgeMartinezG** [comment] 2021-06-22 18:51
- **Version 1.x**
https://odc.ovio.org/?service=WCS&request=GetCoverage&version=1.0.0&coverage=hfs1_sfw_mask&crs=EPSG%3A4326&bbox=92.2%2C9.7%2C101.2%2C28.5&width=1098&height=2304&format=GeoTIFF&time=2021-05-03T10:00:00.000Z

- **Version 2.x**
https://odc.ovio.org/?service=WCS&request=GetCoverage&version=2.0.1&coverageId=hfs1_sfw_mask&subset=longitude(92.17274709800029,101.17001505562291)&subset=latitude(9.67125210200021,28.545538862)&subset=time(%222021-05-03T10:00:00.000Z%22)

**Comment by valpesendorfer** [comment] 2021-06-22 18:55
Sidenote: 

Even if the datatype would be `uint8`, we'd still deal with a 2.4GB array which is not ideal. Moving to a production setup we'd likely use more instances with less RAM (the current single EC2 has 16GB), so it's a good point that the tiff could be too big for a request/response flow. 

Instead of requesting the raster for the entire country, wouldn't it be better to split the workflow up in blocks and send multiple (possibly concurrent) requests?

**Comment by valpesendorfer** [comment] 2021-06-22 19:02
> * **Version 1.x**
>   https://odc.ovio.org/?service=WCS&request=GetCoverage&version=1.0.0&coverage=hfs1_sfw_mask&crs=EPSG%3A4326&bbox=92.2%2C9.7%2C101.2%2C28.5&width=1098&height=2304&format=GeoTIFF&time=2021-05-03T10:00:00.000Z
> * **Version 2.x**
>   https://odc.ovio.org/?service=WCS&request=GetCoverage&version=2.0.1&coverageId=hfs1_sfw_mask&subset=longitude(92.17274709800029,101.17001505562291)&subset=latitude(9.67125210200021,28.545538862)&subset=time(%222021-05-03T10:00:00.000Z%22)

@JorgeMartinezG where does the requested size in the first example 2304 x 1098 come from? The second example using coordinates produces a much bigger array as we have seen.

**Comment by valpesendorfer** [comment] 2021-06-22 22:21
OK - in any case, to me the dimensions from the second request seem about right for the native resolution. So either the first request is for a different resolution or there's another unrelated issue there.

Regarding the issue at hand:

I've did some digging and I think there could be a bug in the upstream codebase in `datacube-ows` ... I'll need to gather some more info and contact the devs.

For  the time being, I'd like to hear your thoughts on

> Instead of requesting the raster for the entire country, wouldn't it be better to split the workflow up in blocks and send multiple (possibly concurrent) requests?

as pulling such big rasters through WCS seems to be generally a not so great idea to me.

**Comment by wadhwamatic** [comment] 2021-06-23 03:23
> as pulling such big rasters through WCS seems to be generally a not so great idea to me.

I agree with this. But I'm also unclear why the size is so large. I though the underlying GeoTIFFs are about 20 mb in size. But maybe I'm mistaken. 

Given the purpose of this request a file, I'm wondering if there's another way of doing this that goes directly to the source on S3?

**Comment by erwagasore** [comment] 2021-06-23 14:54
- From [`DescribeCoverage`](https://docs.geoserver.org/stable/en/user/services/wcs/configuration.html#request-limits) the native format is `image/GeoTIFF`thus when calling `GetCoverage` with `subsets` we should get `image/geotiff`. I am wondering if the `float64` is are data passed to the function which produces the `geotiff`.
- [Here is a conversation regarding this issue on StackExchange](https://gis.stackexchange.com/questions/169863/geoserver-wms-get-original-raster-image-in-highest-resolution) hopefully it can help a little

**Comment by wadhwamatic** [comment] 2021-06-28 07:29
We need to find a solution here. Let's please discuss this week @erwagasore @JorgeMartinezG  and @valpesendorfer

**Comment by valpesendorfer** [comment] 2021-07-06 17:04
After some testing it does seem the issue is on the `datacube-ows` side. I've [raised an issue there](https://github.com/opendatacube/datacube-ows/issues/653#issue-938092877) and we'll see what we can do.

**Comment by wadhwamatic** [comment] 2021-07-06 18:34
> After some testing it does seem the issue is on the `datacube-ows` side. I've [raised an issue there](https://github.com/opendatacube/datacube-ows/issues/653#issue-938092877) and we'll see what we can do.

Thanks for looking into this and raising the issue Valentin

**Comment by valpesendorfer** [comment] 2021-07-08 08:06
A fix has been [merged](https://github.com/opendatacube/datacube-ows/pull/654) in the upstream datacube-ows repository. It's not included in a release yet but I've already implemented it. So the requests should be working now! Please have a look.

I have to mention again that pulling a large raster through WCS isn't a great idea - check the discussion in the [original issue](https://github.com/opendatacube/datacube-ows/issues/653#issue-938092877). 

The request above will work now, but still consumes a lot of memory right until the server's current limit. If and when we move to smaller instances, this will fail.

I'd suggest opening an issue for a replacement of the WCS request.

**Closed** 2021-07-08 08:06 UTC
Labels: bug, priority:high
